[tool.poetry]
name = "cybershadez-backtest riverich-platform"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.1.0"
pandas = "^2.2.3"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
